"""Declarative base + reusable timestamped mixin."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import JSON, BigInteger, DateTime, Integer, MetaData, func
from sqlalchemy.dialects.postgresql import JSONB as PG_JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Use JSONB on PostgreSQL (with indexing/operator benefits) and fall back
# to plain JSON on other dialects (notably SQLite, used by smoke tests).
JSONB = PG_JSONB().with_variant(JSON(), "sqlite")

# SQLite only autoincrements ``INTEGER PRIMARY KEY``, not ``BIGINT``. Using
# this variant keeps BigInteger on Postgres while letting tests run against
# SQLite without writing a custom rowid strategy.
PK_TYPE = BigInteger().with_variant(Integer(), "sqlite")

# Stable, explicit naming convention — Alembic emits deterministic
# constraint names so future autogenerated migrations stay clean.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Project-wide declarative base."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampedMixin:
    """Adds id + created_at + updated_at to a model.

    All Milestone-1 tables share these columns per the SRS.
    """

    id: Mapped[int] = mapped_column(PK_TYPE, primary_key=True, autoincrement=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
